version: '3'

services:
  backend:
    build:
      context: ./
    ports:
      - "8080:8080"
    networks:
      - app-network
  frontend:
    build:
      context: ./roman-numeral-ui
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
